// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace IndiceAcademico_TestCase 
{

    [TestFixture]
    public class DefaultSuiteTest
    {
        IWebDriver driver;
        private IJavaScriptExecutor js;
        [SetUp]
        public void SetUp()
        {
            //driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), new FirefoxOptions().ToCapabilities());

            driver = new FirefoxDriver();
            driver.Manage().Window.Maximize();
            js = (IJavaScriptExecutor)driver;
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }
        [Test]
        public void tC01Login()
        {
            driver.Navigate().GoToUrl("https://intec-academic-system.netlify.app/");
            driver.Manage().Window.Size = new System.Drawing.Size(1550, 878);
            driver.FindElement(By.Id("username")).Click();
            driver.FindElement(By.Id("username")).SendKeys("admin");
            driver.FindElement(By.Id("password")).SendKeys("admin");
            driver.FindElement(By.Id("password")).SendKeys(Keys.Enter);
        }
        [Test]
        public void tC02RegistrarMateria()
        {
            driver.Navigate().GoToUrl("https://intec-academic-system.netlify.app/");
            driver.Manage().Window.Size = new System.Drawing.Size(1319, 692);
            driver.FindElement(By.Id("username")).Click();
            driver.FindElement(By.Id("username")).SendKeys("admin");
            driver.FindElement(By.Id("password")).SendKeys("admin");
            driver.FindElement(By.Id("password")).SendKeys(Keys.Enter);
            driver.FindElement(By.LinkText("Ver Materias")).Click();
            js.ExecuteScript("window.scrollTo(0,200.8000030517578)");
            driver.FindElement(By.Id("code")).Click();
            driver.FindElement(By.Id("code")).SendKeys("IDS309");
            driver.FindElement(By.CssSelector("form")).Click();
            driver.FindElement(By.Id("name")).Click();
            driver.FindElement(By.Id("name")).SendKeys("Foo Bar");
            driver.FindElement(By.CssSelector("form")).Click();
            driver.FindElement(By.Id("credit")).Click();
            driver.FindElement(By.Id("credit")).Click();
            {
                var element = driver.FindElement(By.Id("credit"));
                Actions builder = new Actions(driver);
                builder.DoubleClick(element).Perform();
            }
            driver.FindElement(By.Id("credit")).SendKeys("5");
            driver.FindElement(By.Id("teacher")).Click();
            {
                var dropdown = driver.FindElement(By.Id("teacher"));
                dropdown.FindElement(By.XPath("//option[. = 'Foo Bar']")).Click();
            }
            driver.FindElement(By.CssSelector("option:nth-child(6)")).Click();
            driver.FindElement(By.CssSelector(".button")).Click();
            js.ExecuteScript("window.scrollTo(0,200.8000030517578)");
        }
        [Test]
        public void tC03RegistrarProfesor()
        {
            driver.Navigate().GoToUrl("https://intec-academic-system.netlify.app/");
            driver.Manage().Window.Size = new System.Drawing.Size(1319, 692);
            driver.FindElement(By.Id("username")).Click();
            driver.FindElement(By.Id("username")).SendKeys("admin");
            driver.FindElement(By.Id("password")).SendKeys("admin");
            driver.FindElement(By.CssSelector(".button")).Click();
            {
                var element = driver.FindElement(By.LinkText("Ver Profesores"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
            }
            driver.FindElement(By.LinkText("Ver Profesores")).Click();
            js.ExecuteScript("window.scrollTo(0,0)");
            driver.FindElement(By.Id("name")).Click();
            driver.FindElement(By.Id("name")).SendKeys("Foo Bar");
            driver.FindElement(By.Id("name")).SendKeys(Keys.Enter);
        }
        [Test]
        public void tC04RegistrarEstudiante()
        {
            driver.Navigate().GoToUrl("https://intec-academic-system.netlify.app/");
            driver.Manage().Window.Size = new System.Drawing.Size(1319, 692);
            driver.FindElement(By.Id("username")).Click();
            driver.FindElement(By.Id("username")).SendKeys("admin");
            driver.FindElement(By.Id("password")).SendKeys("admin");
            driver.FindElement(By.Id("password")).SendKeys(Keys.Enter);
            driver.FindElement(By.LinkText("Ver Estudiantes")).Click();
            {
                var element = driver.FindElement(By.LinkText("Ver Estudiantes"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
            }
            driver.FindElement(By.Id("name")).Click();
            driver.FindElement(By.Id("name")).SendKeys("Foo Bar");
            driver.FindElement(By.Id("degree")).Click();
            {
                var dropdown = driver.FindElement(By.Id("degree"));
                dropdown.FindElement(By.XPath("//option[. = 'ICS - Ingeniería en Ciberseguridad']")).Click();
            }
            driver.FindElement(By.CssSelector("optgroup:nth-child(6) > option:nth-child(8)")).Click();
            driver.FindElement(By.CssSelector(".button")).Click();
        }
        [Test]
        public void tC08ActualizarMateria()
        {
            driver.Navigate().GoToUrl("https://intec-academic-system.netlify.app/");
            driver.Manage().Window.Size = new System.Drawing.Size(1319, 692);
            driver.FindElement(By.Id("username")).Click();
            driver.FindElement(By.Id("username")).SendKeys("admin");
            driver.FindElement(By.Id("password")).SendKeys("admin");
            driver.FindElement(By.Id("password")).SendKeys(Keys.Enter);
            js.ExecuteScript("window.scrollTo(0,8.800000190734863)");
            driver.FindElement(By.LinkText("Ver Materias")).Click();
            js.ExecuteScript("window.scrollTo(0,200.8000030517578)");
            driver.FindElement(By.CssSelector("tr:nth-child(3) > td:nth-child(2)")).Click();
            driver.FindElement(By.Id("name")).Click();
            driver.FindElement(By.Id("name")).SendKeys("Bad Bar");
            driver.FindElement(By.Id("credit")).Click();
            driver.FindElement(By.Id("credit")).SendKeys("3");
            driver.FindElement(By.CssSelector(".primary")).Click();
        }
        [Test]
        public void tC10ActualizarEstudiante()
        {
            driver.Navigate().GoToUrl("https://intec-academic-system.netlify.app/");

            driver.Manage().Window.Size = new System.Drawing.Size(1319, 692);
            driver.FindElement(By.Id("username")).Click();
            driver.FindElement(By.Id("username")).SendKeys("admin");
            driver.FindElement(By.Id("password")).SendKeys("admin");
            driver.FindElement(By.Id("password")).SendKeys(Keys.Enter);
            {
                var element = driver.FindElement(By.LinkText("Ver Estudiantes"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
            }
            {
                var element = driver.FindElement(By.TagName("body"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
            }
            driver.FindElement(By.LinkText("Ver Estudiantes")).Click();
            js.ExecuteScript("window.scrollTo(0,24.799999237060547)");
            driver.FindElement(By.Id("name")).Click();
            driver.FindElement(By.Id("name")).SendKeys("Foo Choco Bar");
            driver.FindElement(By.Id("degree")).Click();
            {
                var dropdown = driver.FindElement(By.Id("degree"));
                dropdown.FindElement(By.XPath("//option[. = 'AGN - Administración y Gestión de Negocios']")).Click();
            }
            driver.FindElement(By.CssSelector("optgroup:nth-child(2) > option:nth-child(1)")).Click();
        }
        [Test]
        public void tC09ActualizarProfesor()
        {
            driver.Navigate().GoToUrl("https://intec-academic-system.netlify.app/");
            driver.Manage().Window.Size = new System.Drawing.Size(1319, 692);
            driver.FindElement(By.Id("username")).Click();
            driver.FindElement(By.Id("username")).SendKeys("admin");
            driver.FindElement(By.Id("password")).SendKeys("admin");
            driver.FindElement(By.Id("password")).SendKeys(Keys.Enter);
            driver.FindElement(By.LinkText("Ver Profesores")).Click();
            js.ExecuteScript("window.scrollTo(0,0)");
            driver.FindElement(By.CssSelector("tr:nth-child(5) > td")).Click();
            driver.FindElement(By.Id("name")).Click();
            driver.FindElement(By.Id("name")).SendKeys("Foo Bar McCoffee");
            driver.FindElement(By.CssSelector(".primary")).Click();
        }
    }


}
